[package]
name = "crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
common = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
