[package]
name = "s3-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
