[package]
name = "ddns"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
encoding_rs = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
